# application-prod.yml - Production Configuration
spring:
  application:
    name: ihdrs-backend
  
  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/ihdrs_db}
    username: ${SPRING_DATASOURCE_USERNAME:ihdrs_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ihdrs_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
    open-in-view: false
  
  # Redis Configuration
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    max-threads: 200
    min-spare-threads: 10

# File Storage Configuration
file:
  upload:
    path: /app/uploads/
    max-size: 5242880
    allowed-types: image/png,image/jpeg,image/jpg
  model:
    path: /app/models/

# Model Service Configuration
model-service:
  base-url: ${MODEL_SERVICE_BASE_URL:http://model-service:5000}
  timeout: 30s
  max-retries: 3
  retry-delay: 1s

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:ihdrs_jwt_secret_key_2025_very_long_string_for_security}
  expiration: 86400

# Recognition Configuration
recognition:
  min-confidence-threshold: 0.8
  max-retries: 3
  cache-expire: 86400

# Logging Configuration
logging:
  level:
    root: INFO
    com.ihdrs.backend: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/ihdrs-backend.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
