# application-prod.yml - 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ihdrs}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

model-service:
  base-url: ${MODEL_SERVICE_URL:http://localhost:5000}

jwt:
  secret: ${JWT_SECRET}

file:
  upload:
    path: ${FILE_UPLOAD_PATH:/app/uploads/}
  model:
    path: ${MODEL_PATH:/app/models/}

logging:
  level:
    com.ihdrs.backend: INFO
    root: WARN